name: funix_thieudvfx_foodsaver
description: My graduation thesis.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
  
dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.1
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  injectable: ^2.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  
  meta: ^1.12.0
  retrofit: ^4.0.1
  smartstruct: ^1.4.0
  

dev_dependencies:
  analyzer: ^5.9.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.4.11
  # dart_code_metrics: ^5.6.0
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^2.1.4
  json_serializable: ^6.5.4
  retrofit_generator: ^6.0.0+1
  smartstruct_generator: ^1.4.0

# Assets Generator
flutter_gen:
  output: lib/resources
  line_length: 120
  fonts:
    enabled: false

  integrations:
    flutter_svg: true

# Native Splash
flutter_native_splash:
  color: "#CD3838"
  image: assets/foodsaver_splash.png
  android: true
  ios: true

# App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/foodsaver_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# Internationalization and Localization Generator
flutter_intl:
  enabled: true
  class_name: Lang
  arb_dir: lib/core/localization
  output_dir: lib/core/localization/generated

flutter:
  uses-material-design: true

  assets:
    - 'assets/'
    - 'assets/images/'

  
